### ISSUE TITLE
Mother Poptop can be hit outside arena

### ISSUE THREAD

**Issue by Caue113** [Donmor-d/StarboundTweaks#1]
## Problem
It's possible to hit and kill Mother Poptop with a gun or even a melee weapon (such as lance or sword) without getting inside her arena by only stading near the connectors between caves and the arena.

Image below describes the player's range and the Mother Poptop.

![image](https://user-images.githubusercontent.com/93008613/163067137-67eedd97-2f14-4cd1-b7ca-12ecaf61a58b.png)

## Possible solution(s)
To solve the problem we could:

- Freeze Mother Poptop's spawn and only instance it when the player(s) are inside the over the arena's ground;
- Change the arena generation, so the arena's ground is deeper and melee weapons can't reach her;

**Comment by Donmor-d** [comment]
solved by giving her a pull attack, it just needs some visual refining
